http:
  routers:
    to-service-www:
      entryPoints:
      - web
      - websecure
      rule: "Host(`machineand.me`)"
      service: service-www
      tls:
        certResolver: default
        domains:
          - main: "machineand.me"
            sans:
              - "*.machineand.me"
  services:
    service-www:
      loadBalancer:
        servers:
        - url: "http://10.114.0.3/"
    # ticker:
    #   loadBalancer:
    #     servers:
    #     - url: "http://10.114.0.4/"
