http:
  routers:
    to-service-www:
      entryPoints:
      - web
      - websecure
      rule: "Host(`machineand.me`)"
      service: service-www
      priority: 10
      tls:
        certResolver: default
        domains:
          - main: "machineand.me"
            sans:
              - "*.machineand.me"
    to-service-ticker-backend:
      entryPoints:
      - web
      - websecure
      rule: "Host(`v1.ticker.love`)"
      service: service-ticker-backend
      priority: 10
      tls:
        certResolver: default
        domains:
          - main: "v1.ticker.love"
    default:
      entryPoints:
      - web
      - websecure
      rule: "HostRegexp(`{host:.+}`)"
      service: service-www
      priority: 1
  services:
    service-www:
      loadBalancer:
        servers:
        - url: "http://10.114.0.3/"
    service-ticker-backend:
      loadBalancer:
        servers:
        - url: "http://10.114.0.4:4356"
        - url: "http://10.114.0.4:4357"
        - url: "http://10.114.0.4:4358"
    # ticker:
    #   loadBalancer:
    #     servers:
    #     - url: "http://10.114.0.4/"
