http:
  routers:
    to-service-www:
      rule: Host(`machineand.me`)
      service: service-www
      entryPoints:
        - web
        - websecure
      priority: 1
      tls:
        certResolver: default
        domains:
          - main: "machineand.me"
    to-service-ticker-backend:
      rule: Host(`v1.ticker.love`)
      service: service-ticker-backend
      entryPoints:
        - websecure
      priority: 2
      tls:
        certResolver: default
        domains:
          - main: "v1.ticker.love"
    to-service-codetee:
      rule: Host(`codetee.machineand.me`)
      service: service-codetee
      entryPoints:
        - websecure
      priority: 2
      tls:
        certResolver: default
        domains:
          - main: "codetee.machineand.me"
    the-default:
      entryPoints:
        - web
        - websecure
      rule: HostRegexp(`{host:.+}`)
      service: service-www
      priority: 3
  services:
    service-www:
      loadBalancer:
        servers:
          - url: "http://10.114.0.3/"
    service-ticker-backend:
      loadBalancer:
        servers:
          - url: "http://10.114.0.4:4356"
          - url: "http://10.114.0.4:4357"
          - url: "http://10.114.0.4:4358"
    service-codetee:
      loadBalancer:
        servers:
          - url: "http://10.114.0.6:8080"
