global:
  checkNewVersion: yes
  sendAnonymousUsage: yes
log:
  level: "DEBUG"
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
api:
 insecure: yes
 dashboard: yes
acme:
  email: "billionspoint@gmail.com"
  storage: "acme.json"
  entryPoint: "https"
  onHostRule: yes
  httpChallenge:
    entryPoint: "http"
providers:
  file:
    filename: /opt/traefik/services.yml
    watch: no
