global:
  checkNewVersion: yes
  sendAnonymousUsage: yes
entryPoints:
  web:
    address: :80
  websecure:
    address: :443
accessLog:
  filePath: /var/log/traefik.access.log
  format: json
  fields:
    defaultMode: keep
    headers:
      defaultMode: keep
      names:
        Authorization: drop
        Cookie: drop
certificatesResolvers:
  default:
    acme:
      email: "billionspoint@gmail.com"
      storage: "/opt/traefik//acme.json"
      tlschallenge: yes
metrics:
  datadog: {}
tracing:
  datadog: {}
log:
  level: "INFO"
api:
 insecure: no
 dashboard: no
providers:
  file:
    filename: /opt/traefik/services.yml
    watch: no
