name: Release
on:
  push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: "${{ secrets.githubPAT }}"
          submodules: recursive

      - name: Write ssh key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.sshKey }}" > ~/.ssh/id_rsa
          echo "${{ secrets.sshPubKey }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Install datadog role
        run: ansible-galaxy install datadog.datadog

      - name: Ansible some playbook
        run: ansible-playbook ../playbook-traefik.yaml
        working-directory: ansible